### PR TITLE
Use DeviceKit package to get device info

### PR DESCRIPTION
**Pull request by schmidt9**

### CODE REVIEW

**Comment by dxCLA** [comment]
[CLA assistant check](https://cla.devexperts.com/devexperts/suitcase?pullRequest=7) <br/>All committers have signed the CLA.

**Comment by rzakhar** [comment]
Thank you for a PR! Can you please verify that modelName returns exactly the same result for the existing simulators? This is important for the backwards compatibility

**Comment by schmidt9** [comment]
> Thank you for a PR! Can you please verify that modelName returns exactly the same result for the existing simulators? This is important for the backwards compatibility

Yes there are some differences

```
Defferences found DeviceKit / SUITCase:

iPad Mini 2 != iPad mini 2
iPhone Xs Max != iPhone XS Max
iPad Mini 3 != iPad mini 3
iPad Mini (5th generation) != iPad mini (5th generation)
iPhone Xʀ != iPhone XR
iPhone Xs != iPhone XS
iPad Mini 4 != iPad mini 4
iPad11,5 != iPad Air (3rd generation)
iPad Mini != iPad mini
```

**Comment by schmidt9** [comment]
As you see the most have just different letter case, and just one is absent in DeviceKit `iPad11,5 != iPad Air (3rd generation)`

**Comment by schmidt9** [comment]
> and just one is absent in DeviceKit `iPad11,5 != iPad Air (3rd generation)`

this one could be added to DeviceKit fork / PR

**Comment by rzakhar** [comment]
1. Can you please check what exact simulators identifiers are used by the Xcode 14? It might be that we don't need to update DeviceKit at all.
2. It looks like the current implementation will add "Simulator ..." prefix everywhere, and that is extremely bad for the backwards compatibility. At the moment, we don't support testing on the real devices, so we don't need this prefix.
3. iPad minis are marketed with a lowercase "mini". It seems like there is a little issue in the DeviceKit. Not a huge problem though, so we don't have to do anything. 
4. Please consider using "safeDescription" instead of "description". It will be safer to the filenames, I suppose

**Comment by schmidt9** [comment]
> 3\. iPad minis are marketed with a lowercase "mini". It seems like there is a little issue in the DeviceKit. Not a huge problem though, so we don't have to do anything.

With `safeDescription` diff list is slightly different

```
iPad Mini 4 != iPad mini 4
iPad Mini 3 != iPad mini 3
iPad Mini (5th generation) != iPad mini (5th generation)
iPad Mini != iPad mini
iPad Mini 2 != iPad mini 2
iPad11,5 != iPad Air (3rd generation)
```

**Comment by schmidt9** [comment]
> 1. Can you please check what exact simulators identifiers are used by the Xcode 14? It might be that we don't need to update DeviceKit at all.

Example output:
`Optional("iPhone15,3")` gives `Simulator (iPhone 14 Pro Max)`

**Comment by schmidt9** [comment]
> 2\. It looks like the current implementation will add "Simulator ..." prefix everywhere, and that is extremely bad for the backwards compatibility. At the moment, we don't support testing on the real devices, so we don't need this prefix.

We can strip Simulator part using regex

```
    private static let simulatorRegex = try! NSRegularExpression(pattern: "Simulator \\((.*)\\)")
    
    static var modelName: String {
        var result = DeviceKit.Device.current.safeDescription
        
        if isSimulator {
            guard let match = simulatorRegex.firstMatch(in: result, range: NSMakeRange(0, result.count)) else {
                return result
            }
            
            let range = match.range(at: 1)
            result = (result as NSString).substring(with: range)
        }
        
        return result
    }
```

and add a test for it

```
    func testSimulatorModelName() {
        if UIDevice.isSimulator {
            let modelName = UIDevice.modelName
            XCTAssertFalse(modelName.lowercased().contains("simulator"))
        }
    }
```

**Comment by schmidt9** [comment]
I can commit these patches if they are OK for you

**Comment by rzakhar** [comment]
You should consider using replacingOccurrences(of:with:) instead of regexp matching, since it is so trivial

**Comment by schmidt9** [comment]
> You should consider using replacingOccurrences(of:with:) instead of regexp matching, since it is so trivial

```
    static var modelName: String {
        var result = DeviceKit.Device.current.safeDescription
        
        if isSimulator {
            result = result
                .replacingOccurrences(of: "Simulator (", with: "")
                .replacingOccurrences(of: ")", with: "")
        }
        
        return result
    }
```

**Comment by schmidt9** [comment]
Should I also add this test? If yes to an existing or to a separate class?
```
    func testSimulatorModelName() {
        if UIDevice.isSimulator {
            let modelName = UIDevice.modelName
            XCTAssertFalse(modelName.lowercased().contains("simulator"))
        }
    }
```

**Comment by rzakhar** [comment]
> Should I also add this test? If yes to an existing or to a separate class?
> 
> ```
>     func testSimulatorModelName() {
>         if UIDevice.isSimulator {
>             let modelName = UIDevice.modelName
>             XCTAssertFalse(modelName.lowercased().contains("simulator"))
>         }
>     }
> ```

That’s a good idea to add a separate class. You can also add checks that the modelName only contains regular letters, numbers and brackets

**Comment by schmidt9** [comment]
@rzakhar please check additional commit

**Review by rzakhar — APPROVED** [review]
Awesome job, thank you!

**Pull request merged**
